Host:
    ip_addr: 192.168.10.109
    user: pi
    password: mine7720
    Receivers:
        - Receiver:
            port : 8081
            station_name: Yokota ATIS
            freq: 128.4M
            mode: am
            additional_options: -s 32000 -g40 -p 100

        - Receiver:
            port : 8082
            station_name: Tokyo control West sector
            freq: 120.5M
            mode: am
            additional_options: -s 32000 -g40 -p 100
sock2wav:
    path: /home/katsuwo/work/sock2wav/

# WBFM受信時パラメータ
# rtl_fm -f 80.0M -M wbfm -r 32k -E deemp -A fast -p 100