Host:
    ip_addr: 192.168.10.1
    user: user
    password: passwd

    Receivers:
        - Receiver:
            device_index: 0
            rtl_tcp_port: 1234
            grc_out_port : 8081
            socat_out_port : 8091
            station_name: Tokyo Control West Sector
            freq: 120.5e6
            gain: 49.6
            squelch: -22.4
            freq_correct: 32.0
            mode: am
            additional_options:

        - Receiver:
            device_index: 1
            rtl_tcp_port: 1235
            grc_out_port: 8082
            socat_out_port: 8092
            station_name: Yokota ATIS
            freq: 128.4e6
            gain: 49.6
            squelch: -15.0
            freq_correct: 32.0
            mode: am
            additional_options:

Recorder:
    GRC_Recorder:
        pre_execute_cmd: export DISPLAY=:0.0
        script_path: /home/xxxxx/work/GnuRadio_AirbandReceiver/AM_Receiver_NOGUI_with_Commandline.py
        python27_path: python2

    sock2wav:
        path: /home/xxxxx/work/sock2wav/build/sock2wav
        output_path: /home/xxxxx/work/SDR_Audio_Data/wav
        # sock2wave will close file at the turn of the minute when file_split_time is set to -1
        # otherwise, sock2wave writeto file for the number of seconds specified in file_split_time
        file_split_Time: -1

    hostkey:
        known_hosts_file: /home/xxxxx/.ssh/known_hosts

    lame:
        output_path: /home/xxxxx/work/SDR_Audio_Data/mp3
        path: lame
        options: -b 48

S3_STORAGE:
    S3_endpoint_url: 192.168.0.4:9000
    S3_access_key_id: your access key
    S3_secret_access_key: your secret key
    S3_bucket_name: SDR
